name: Build Lucis-Sub Executable
run-name: No${{ github.run_number }} |🚀 Build Lucis-Sub by @${{ github.actor }} | ${{ github.event.repository.updated_at }}

on:
  push:
    tags:
      - 'v*'  # 当你推送以 v 开头的标签（如 v1.0）时，自动打包

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt6 beautifulsoup4

      - name: Build with PyInstaller
        run: |
          pyinstaller --onedir --noconsole --name "Lucis-Sub" --icon "favicon.ico" --add-data "favicon.ico;." --add-data "logo.png;." --add-data "like.png;." main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lucis-Sub-Dist
          path: dist/Lucis-Sub/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # 修改这里：指向你刚才压缩好的 zip 包
          files: Lucis_Sub_Substack_Windows_V20260618_beta.zip
          # 设置 Release 的标题
          name: Lucis_Sub_Substack_Windows_V20260618_beta
